New "chroot to share" option
hassio-addons/addon-ftp pull request #129
Opened 2023-01-14 16:25 UTC by hugoKs3

# Proposed Changes

This PR provides a new option at user level to allow setting the root of the user to the "/share" folder.
Such an option is especially useful for cameras automatic screenshot uploads which do not allow to specify a folder and only upload at the root of the user.

Note: Included in this PR is the update of OpenSSL dependency to 3.0.7-r**2**

2023-01-15 12:41 UTC, frenck requested changes

2023-01-15 12:41 UTC, frenck commented on ftp/rootfs/etc/s6-overlay/s6-rc.d/init-users/run
> +    fi
This is conflicting with the other directory options (e.g., what is access to share isn't provided in the configuration, or access to config was provided as well?)

That should be handled.

../Frenck

2023-01-15 17:19 UTC, hugoKs3 commented on ftp/rootfs/etc/s6-overlay/s6-rc.d/init-users/run
> +    fi
Thanks for the feedback @frenck.
You're right, I did it a bit in a hurry.
I just updated the PR with a more elegant way to manage this option.

Looking forward for your review.

2023-01-17 17:51 UTC, hugoKs3 commented
@frenck, does this last change fit with your requirements?

2023-01-21 19:12 UTC, hugoKs3 commented
Linked to #10

2023-02-05 14:53 UTC, hugoKs3 commented
Hello @frenck,
Have you been able to review the PR following the changes I made after you first review?
Thank you.

2023-03-16 08:20 UTC, closed without merging